name: APK Build
run-name: Build ${{ github.event.inputs.game }}

on:
  workflow_dispatch:
    inputs:
      game:
        description: "Select Game"
        required: true
        default: "wet-wealth"
        type: choice
        options:
          - wet-wealth
          - horny-villa
          - ark-recode
          - mafia-queens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v6
      # - uses: actions/setup-java@v5
      #   with:
      #     distribution: "temurin" # See 'Supported distributions' for available options
      #     java-version: "21"

      # - name: Setup apksigner
      #   run: |
      #     echo "$ANDROID_HOME/build-tools/36.1.0" >> $GITHUB_PATH

      # - name: Setup apktool
      #   run: |
      #     curl -L -o /usr/local/bin/apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
      #     curl -L -o /usr/local/bin/apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.12.1/apktool_2.12.1.jar
      #     chmod +x /usr/local/bin/apktool /usr/local/bin/apktool.jar

      - run: |
          download_url=$(curl -w "%{url_effective}\n" -ILsS https://www.nutaku.net/games/wet-wealth/app-update)

      # - name: Build APK
      #   env:
      #     SIGN_KS_PASS: ${{ secrets.SIGN_KS_PASS }}
      #   run: ./build.sh ${{ github.event.inputs.game }}

      # - name: Build Name
      #   run: |
      #     filename=$(ls dist)
      #     echo "BUILD_NAME=${filename%.*}" >> $GITHUB_ENV

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.BUILD_NAME }}
      #     path: |
      #       dist/*.apk
